services:
  basicstation:
    image: ssenchyn/basicstation:aarch64-latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host

    volumes:
      - config:/app/config

    environment:
      MODEL: "REWAN1012"
      GW_POWER_EN_GPIO: "GPIO119"
      GW_RESET_GPIO: "GPIO122"
      GW_POWER_EN_LOGIC: 0
      CS_KEY: ${CS_KEY}
      TC_URI: ${TC_URI}

volumes:
  config:

#secrets:
#  tc.uri:
#    file: tc.uri
#  tc.trust:
#    file: tc.trust
#  tc.crt:
#    file: tc.crt
#  tc.key:
#    file: tc.key
