services:
  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host

    secrets:
      - tc.uri
      - tc.trust
      - tc.crt
      - tc.key

    volumes:
      - ./config:/app/config

    environment:
      MODEL: "SX1301"
      GW_POWER_EN_GPIO: "GPIO119"
      GW_RESET_GPIO: "GPIO122"
      GW_POWER_EN_LOGIC: 0

secrets:
 tc.uri:
   file: tc.uri
 tc.trust:
   file: tc.trust
 tc.crt:
   file: tc.crt
 tc.key:
   file: tc.key
